server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${mi_repair.datasource.driver-class-name}
      url: jdbc:mysql://${mi_repair.datasource.host}:${mi_repair.datasource.port}/${mi_repair.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${mi_repair.datasource.username}
      password: ${mi_repair.datasource.password}
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mi.repair.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

#日志配置
logging:
  level:
    com.mi_repair: debug
    org.springframework: warn

mi-repair:
  jwt:
    # 设置jwt签名加密时使用的密钥
    user-secret-key: mi-repair-user
    # 设置jwt令牌过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: token
    worker-secret-key: mi-repair-worker
    worker-ttl: 7200000
    worker-token-name: token
  minio:
    endpoint: http://192.168.101.65:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucket:
      files: picture
      videofiles: video

